import React, { useState, useEffect } from 'react';
import { postsApi, miscApi } from '../../api';
import { useAuth } from '../../context/AuthContext';
import { FileText, Plus, X, ArrowLeft, Trash2, Edit2, Sparkles, BookOpen } from 'lucide-react';
import toast from 'react-hot-toast';
import '../../assets/css/Articles.css';

export default function Articles() {
  const { user } = useAuth();
  const [articles, setArticles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedArticle, setSelectedArticle] = useState(null);
  const [showCreateModal, setShowCreateModal] = useState(false);

  // AI Assistant states
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiGenerating, setAiGenerating] = useState(false);

  // Form state
  const [form, setForm] = useState({
    title: '',
    body: ''
  });

  useEffect(() => {
    loadArticles();
  }, []);

  const loadArticles = async () => {
    setLoading(true);
    try {
      const res = await postsApi.getArticles();
      if (res.data) {
        setArticles(Array.isArray(res.data) ? res.data : []);
      }
    } catch (err) {
      console.error('Error fetching articles', err);
      setArticles([]);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateSubmit = async (e) => {
    e.preventDefault();
    try {
      await postsApi.createArticle({ article: form });
      toast.success('Article published!');
      setShowCreateModal(false);
      setForm({ title: '', body: '' });
      loadArticles();
    } catch (err) {
      toast.error('Failed to publish article');
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Delete this article?')) return;
    try {
      await postsApi.deleteArticle(id);
      toast.success('Article deleted');
      setSelectedArticle(null);
      loadArticles();
    } catch (err) {
      toast.error('Failed to delete article');
    }
  };

  const handleAiArticleGenerate = async () => {
    if (!aiPrompt.trim()) {
      toast.error('Please enter a brief outline or title for the AI');
      return;
    }
    setAiGenerating(true);
    try {
      const res = await miscApi.generateArticleContent({ prompt: aiPrompt });
      if (res.data) {
        setForm({
          title: res.data.title || aiPrompt,
          body: res.data.content || res.data.body || res.data
        });
        toast.success('Draft generated by Sangam AI!');
      }
    } catch (err) {
      toast.error('AI features are offline');
    } finally {
      setAiGenerating(false);
    }
  };

  return (
    <div className="articles-page-container">
      {selectedArticle ? (
        /* Detailed Article Reader */
        <div className="article-reader-panel glass">
          <button onClick={() => setSelectedArticle(null)} className="back-btn">
            <ArrowLeft size={16} /> Back to articles
          </button>

          <article className="article-content">
            <header className="article-header">
              <h1>{selectedArticle.title}</h1>
              <div className="article-meta">
                <span>By @{selectedArticle.user?.name || 'Author'}</span>
                <span>•</span>
                <span>{new Date(selectedArticle.created_at).toLocaleDateString()}</span>
              </div>
            </header>

            <div className="article-body">
              {selectedArticle.body?.split('\n').map((para, i) => (
                <p key={i}>{para}</p>
              ))}
            </div>

            {selectedArticle.user_id === user.id && (
              <footer className="article-footer">
                <button onClick={() => handleDelete(selectedArticle.id)} className="delete-btn">
                  <Trash2 size={16} /> Delete Article
                </button>
              </footer>
            )}
          </article>
        </div>
      ) : (
        /* Article Index Grid */
        <>
          <div className="articles-header-row">
            <div>
              <h1>Articles Ledger</h1>
              <p>Explore long-form insights and engineering articles written by creators.</p>
            </div>
            <button onClick={() => setShowCreateModal(true)} className="glow-btn publish-article-btn">
              <Plus size={16} /> Write Article
            </button>
          </div>

          {loading ? (
            <div className="articles-loader">
              <div className="premium-spinner"></div>
              <p>Syncing log files...</p>
            </div>
          ) : articles.length > 0 ? (
            <div className="articles-grid">
              {articles.map(art => (
                <div key={art.id} onClick={() => setSelectedArticle(art)} className="glass article-card">
                  <div className="article-icon-wrapper">
                    <BookOpen size={20} color="var(--accent-color)" />
                  </div>
                  <h3>{art.title}</h3>
                  <span className="article-author">By @{art.user?.name || 'Author'}</span>
                  <p className="article-preview">{art.body?.slice(0, 120)}...</p>
                  <span className="read-more-lbl">Read article →</span>
                </div>
              ))}
            </div>
          ) : (
            <div className="articles-empty">
              <FileText size={48} />
              <p>No articles indexed in this registry.</p>
            </div>
          )}
        </>
      )}

      {/* Write Article Modal */}
      {showCreateModal && (
        <div className="modal-overlay" onClick={() => setShowCreateModal(false)}>
          <div className="modal-content glass wide" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Write New Article</h3>
              <button onClick={() => setShowCreateModal(false)} className="modal-close-btn">
                <X size={18} />
              </button>
            </div>

            <div className="modal-form-scroll">
              {/* AI generator assistance */}
              <div className="ai-assist-box glass">
                <div className="ai-label-row">
                  <span><Sparkles size={14} color="var(--accent-color)" /> Sangam AI Draft Assistant</span>
                </div>
                <div className="ai-input-row">
                  <input 
                    type="text" 
                    placeholder="Enter draft topic (e.g. Future of decentralized UX)" 
                    value={aiPrompt}
                    onChange={(e) => setAiPrompt(e.target.value)}
                  />
                  <button type="button" onClick={handleAiArticleGenerate} disabled={aiGenerating} className="glow-btn">
                    {aiGenerating ? 'Generating...' : 'Generate draft'}
                  </button>
                </div>
              </div>

              <form onSubmit={handleCreateSubmit} className="article-main-form">
                <div className="form-group">
                  <label>Article Title</label>
                  <input 
                    type="text" 
                    value={form.title} 
                    onChange={(e) => setForm({ ...form, title: e.target.value })} 
                    placeholder="Headline title..."
                    required 
                  />
                </div>

                <div className="form-group">
                  <label>Content Body</label>
                  <textarea 
                    value={form.body} 
                    onChange={(e) => setForm({ ...form, body: e.target.value })} 
                    rows="10" 
                    placeholder="Write article details..."
                    required
                  />
                </div>

                <button type="submit" className="glow-btn modal-submit-btn">Publish Article</button>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
